use_frameworks!

platform :ios, '15.0'

target 'SwiftUiCustomCalendar_Example' do
  pod 'SwiftUiCustomCalendar', :path => '../'

  target 'SwiftUiCustomCalendar_Tests' do
    inherit! :search_paths

    
  end
end
